In [64]:
import numpy as np
from torch.utils.data import DataLoader
import torch


dataset=np.load('/home/deniz/catkin_ws/src/feedback_controller/fbc/neural_network/data/torobo/815_trajs_static/trajectories.npy',allow_pickle=True, encoding='latin1')

print(dataset[0].shape)
#print(dataset[0])
for i in dataset[0]:
    print(i)

(50, 11)
[ 6.          1.59414354  1.06154834  0.63332647  1.33561378 -1.21243785
 -0.63236132  0.8087251   0.6        -0.1         1.15      ]
[ 7.          1.58696758  1.05253152  0.63619486  1.3378175  -1.21100521
 -0.64060515  0.80626303  0.6        -0.1         1.15      ]
[ 8.          1.5675012   1.02800195  0.64410495  1.34364419 -1.20299736
 -0.66140731  0.79920097  0.6        -0.1         1.15      ]
[ 9.          1.55551103  1.0128947   0.64897425  1.34723643 -1.19815595
 -0.67425441  0.79485962  0.6        -0.1         1.15      ]
[10.          1.54330572  0.99751624  0.65393121  1.35089274 -1.19321795
 -0.68732808  0.79043947  0.6        -0.1         1.15      ]
[11.          1.53143371  0.98255777  0.6587528   1.35444917 -1.18841413
 -0.70004421  0.78613998  0.6        -0.1         1.15      ]
[12.          1.51495669  0.96283751  0.66378     1.36090338 -1.18402378
 -0.71610248  0.78306286  0.6        -0.1         1.15      ]
[13.          1.4995586   0.94521564  0.667186

In [65]:
file_name = "texts/output_normilez.txt"


# Open the file in write mode ('w')
with open(file_name, 'w') as f:

    for i in dataset[0]:

        f.write(str(i[15:22])+"\n")
    
    # Iterate over the list


In [66]:


dataset2=np.load('/home/deniz/catkin_ws/src/feedback_controller/fbc/neural_network/data/torobo/815_trajs_static/obs.npy',allow_pickle=True, encoding='latin1')

print(dataset2.shape)
print(dataset2[0])




(144, 50, 3)
[[6
  array([ 1.59414354,  1.06154834,  0.63332647,  1.33561378, -1.21243785,
         -0.63236132,  0.8087251 ])
  array([ 0.6 , -0.1 ,  1.15])]
 [7
  array([ 1.58696758,  1.05253152,  0.63619486,  1.3378175 , -1.21100521,
         -0.64060515,  0.80626303])
  array([ 0.6 , -0.1 ,  1.15])]
 [8
  array([ 1.5675012 ,  1.02800195,  0.64410495,  1.34364419, -1.20299736,
         -0.66140731,  0.79920097])
  array([ 0.6 , -0.1 ,  1.15])]
 [9
  array([ 1.55551103,  1.0128947 ,  0.64897425,  1.34723643, -1.19815595,
         -0.67425441,  0.79485962])
  array([ 0.6 , -0.1 ,  1.15])]
 [10
  array([ 1.54330572,  0.99751624,  0.65393121,  1.35089274, -1.19321795,
         -0.68732808,  0.79043947])
  array([ 0.6 , -0.1 ,  1.15])]
 [11
  array([ 1.53143371,  0.98255777,  0.6587528 ,  1.35444917, -1.18841413,
         -0.70004421,  0.78613998])
  array([ 0.6 , -0.1 ,  1.15])]
 [12
  array([ 1.51495669,  0.96283751,  0.66378   ,  1.36090338, -1.18402378,
         -0.71610248,  0.78306

In [67]:
file_name2 = "texts/output_obs.txt"
# Open the file in write mode ('w')
with open(file_name2, 'w') as f:
    for i in dataset2[0]:
        f.write(str(i[1]) + "\n")
    # Iterate over the list

In [68]:
dataset3=np.load('/home/deniz/catkin_ws/src/feedback_controller/fbc/neural_network/data/torobo/815_trajs_static/trajectories_normalized.npy',allow_pickle=True, encoding='latin1')

start_state=[ 0.47882179,  0.760346,    0.54813094,  1.52469416, -2.61592815, -0.88263202,  2.04225624]

state_tensor=start_state

file_name2 = "texts/output_sim.txt"
# Open the file in write mode ('w')
count=0
state_tensor=torch.tensor(start_state)

with open(file_name2, 'w') as f:
    for j in dataset3[1]:
        delta_pos=j[15:22]
        print(state_tensor)
        delta_pos_tensor=torch.tensor(delta_pos)
        state_tensor=state_tensor+delta_pos_tensor
        print(delta_pos_tensor)
        print(state_tensor)
        f.write(str(delta_pos) + "\n")
        print('end  ------------------------------------------------------------------------')



tensor([ 0.4788,  0.7603,  0.5481,  1.5247, -2.6159, -0.8826,  2.0423])
tensor([-0.0055, -0.0057,  0.0016,  0.0011,  0.0064, -0.0071, -0.0074],
       dtype=torch.float64)
tensor([ 0.4733,  0.7546,  0.5497,  1.5258, -2.6096, -0.8897,  2.0349],
       dtype=torch.float64)
end  ------------------------------------------------------------------------
tensor([ 0.4733,  0.7546,  0.5497,  1.5258, -2.6096, -0.8897,  2.0349],
       dtype=torch.float64)
tensor([-0.0171, -0.0176,  0.0042,  0.0060,  0.0159, -0.0193, -0.0186],
       dtype=torch.float64)
tensor([ 0.4563,  0.7370,  0.5539,  1.5318, -2.5936, -0.9091,  2.0163],
       dtype=torch.float64)
end  ------------------------------------------------------------------------
tensor([ 0.4563,  0.7370,  0.5539,  1.5318, -2.5936, -0.9091,  2.0163],
       dtype=torch.float64)
tensor([-0.0100, -0.0103,  0.0025,  0.0035,  0.0094, -0.0114, -0.0110],
       dtype=torch.float64)
tensor([ 0.4462,  0.7267,  0.5563,  1.5353, -2.5843, -0.9204,  2.0054],


In [69]:
dataset_full=np.load('/home/deniz/catkin_ws/src/feedback_controller/fbc/neural_network/data/torobo/815_trajs_static/trajectories_normalized.npy',allow_pickle=True, encoding='latin1')

dataset110=[]
dataset34=[]

rand_l=np.array([i for i in range(144)])

np.random.shuffle(rand_l)
print(rand_l)
for i in range(110):
    dataset110.append(dataset_full[rand_l[i]])
for i in range(110,144):
    dataset34.append(dataset_full[rand_l[i]])


np.save('/home/deniz/catkin_ws/src/feedback_controller/fbc/neural_network/data/torobo/815_trajs_static/trajectories_normalized_110.npy',dataset110)
np.save('/home/deniz/catkin_ws/src/feedback_controller/fbc/neural_network/data/torobo/815_trajs_static/trajectories_normalized_34.npy',dataset34)



[140  52  38  72  76  81 117 116 129  59  49 119 110 118   7 108  28  50
  47  98  64  48  65  94 122  45 126 125 135  53 139  43  35   0  88  56
 113  85  17  34  73 131  40   3 106  20  75  22 124 132  44  62  70   4
  51  69  87   2  68  32  24 137   8 114  71 120  14  58  36 115  25 134
 112 105  61  26  11  60 141  15  90  33  66  39 121  41 107  97  54  82
  46 143 109  37  29  30  27  74  99 102   1  63  10  31   5  91 136  84
  83  86 138  77  96 127  16 142  12 104  79  55 123   6  19  23  18  57
  42  80  67  89 101 128  21  92  78  13 103 100   9 130 111 133  93  95]
